INSERT INTO USERS 
(CEDUSER, PASSUSER, NAMEUSER, SECOND_NAMEUSER, LASTNAMEUSER, SECOND_LASTNAMEUSER, STATUSUSER, ROLEUSER, QUESTUSER, ANSWERUSER)
VALUES
(1058, '$2a$10$3UJdnxvdeIUxQff1r4uBQeKHIjJn2U2g2axUVPp25MD3tRGPUXpba', 'Jesus', 'Eduardo', 'Lasso', 'Muñoz', 'Active', 'Doctor', 'Pet name?', 'Rocky'),
