PRAGMA foreign_keys = ON;

CREATE TABLE USERS(
    CODUSER INTEGER PRIMARY KEY AUTOINCREMENT,
    CEDUSER INTEGER NOT NULL UNIQUE,
    PASSUSER TEXT NOT NULL,
    NAMEUSER TEXT NOT NULL,
    SECOND_NAMEUSER TEXT,
    LASTNAMEUSER TEXT NOT NULL,
    SECOND_LASTNAMEUSER TEXT,
    STATUSUSER TEXT NOT NULL DEFAULT 'Active',
    TYPEUSER TEXT NOT NULL,
    CHECK (CEDUSER > 0),
    CHECK (STATUSUSER IN ('Active', 'Inactive')),
    CHECK (TYPEUSER IN ('Doctor', 'Scheduler', 'Patient'))
);

CREATE TABLE DOCTOR(
    CODDOC INTEGER PRIMARY KEY AUTOINCREMENT,
    CODUSER INTEGER NOT NULL,
    GENDOC TEXT NOT NULL,
    PHONEMED TEXT,
    STATUSDOC TEXT NOT NULL DEFAULT 'Active',
    FOREIGN KEY (CODUSER) REFERENCES USERS(CODUSER),
    CHECK (STATUSDOC IN ('Active', 'Inactive')),
    CHECK (GENDOC IN ('Male', 'Female'))
);
