DROP TABLE USERS;
DROP TABLE PROFESSIONAL;
DROP TABLE PATIENT;
DROP TABLE APPOINTMENT;

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS USERS(
    CODUSER INTEGER PRIMARY KEY AUTOINCREMENT,
    CEDUSER INTEGER NOT NULL UNIQUE,
    PASSUSER TEXT NOT NULL,
    NAMEUSER TEXT NOT NULL,
    SECOND_NAMEUSER TEXT,
    LASTNAMEUSER TEXT NOT NULL,
    SECOND_LASTNAMEUSER TEXT,
    STATUSUSER TEXT NOT NULL DEFAULT 'Active',
    ROLEUSER TEXT NOT NULL,
    QUESTUSER TEXT NOT NULL,
    ANSWERUSER TEXT NOT NULL,
    CHECK (CEDUSER > 0),
    CHECK (STATUSUSER IN ('Active', 'Inactive')),
    CHECK (ROLEUSER IN ('Professional', 'Admin', 'Patient'))
);

CREATE TABLE IF NOT EXISTS PROFESSIONAL(
    CODPROF INTEGER PRIMARY KEY AUTOINCREMENT,
    CODUSER INTEGER NOT NULL,
    GENPROF TEXT NOT NULL,
    PHONEPROF TEXT,
    STATUSPROF TEXT NOT NULL DEFAULT 'Active',
    TYPEPROF TEXT NOT NULL DEFAULT 'General',
    SPECIALITYPROF TEXT NOT NULL,
    ATTENTIONINTERVAL INTEGER NOT NULL,
    FOREIGN KEY (CODUSER) REFERENCES USERS(CODUSER),
    CHECK (STATUSPROF IN ('Active', 'Inactive')),
    CHECK (GENPROF IN ('Male', 'Female', 'Otro')),
    CHECK (TYPEPROF IN ('Doctor', 'Therapist')),
    CHECK (SPECIALITYPROF IN ('Neural_Therapy', 'Chiropractor', 'Physiotherapy'))
);


CREATE TABLE IF NOT EXISTS PATIENT (
    CODPATIENT INTEGER PRIMARY KEY AUTOINCREMENT,
    IDPATIENT INTEGER NOT NULL UNIQUE,
    NAMEPATIENT TEXT NOT NULL,
    SECOND_NAMEPATIENT TEXT,
    LASTNAMEPATIENT TEXT NOT NULL,
    SECOND_LASTNAMEPATIENT TEXT,
    PHONE_PATIENT INTEGER,
    DATE_BIRTH_PATIENT TEXT,
    GENDER_PATIENT TEXT NOT NULL
    CHECK (GENDER_PATIENT IN ('Male', 'Female', 'Other'))
);

CREATE TABLE IF NOT EXISTS APPOINTMENT (
    CODAPP INTEGER PRIMARY KEY AUTOINCREMENT,
    CODPROF INTEGER NOT NULL,
    CODPATIENT INTEGER NOT NULL,
    DATEAPP DATE,
    TIMEAPP TIME,
    DESCAPP TEXT,
    STATUSAPP TEXT NOT NULL,
    FOREIGN KEY (CODPROF) REFERENCES PROFESSIONAL(CODPROF),
    FOREIGN KEY (CODPATIENT) REFERENCES PATIENT(CODPATIENT),
    CHECK (STATUSAPP IN ('Created', 'Attended', 'Rescheduled', 'NoAttended', 'Canceled'))
);

COMMIT;
