PRAGMA foreign_keys = ON;


CREATE TABLE IF NOT EXISTS ADMIN(
    CODADMIN INTEGER PRIMARY KEY AUTOINCREMENT,
    USERADMIN TEXT NOT NULL,
    PASSADMIN TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS USERS(
    CODUSER INTEGER PRIMARY KEY AUTOINCREMENT,
    CEDUSER INTEGER NOT NULL UNIQUE,
    PASSUSER TEXT NOT NULL,
    NAMEUSER TEXT NOT NULL,
    SECOND_NAMEUSER TEXT,
    LASTNAMEUSER TEXT NOT NULL,
    SECOND_LASTNAMEUSER TEXT,
    STATUSUSER TEXT NOT NULL DEFAULT 'Active',
    ROLEUSER TEXT NOT NULL,
    QUESTUSER TEXT NOT NULL,
    ANSWERUSER TEXT NOT NULL,
    CHECK (CEDUSER > 0),
    CHECK (STATUSUSER IN ('Active', 'Inactive')),
    CHECK (ROLEUSER IN ('Doctor', 'Scheduler', 'Patient'))
);

CREATE TABLE IF NOT EXISTS PROFESSIONAL(
    CODDOC INTEGER PRIMARY KEY AUTOINCREMENT,
    CODUSER INTEGER NOT NULL,
    GENDOC TEXT NOT NULL,
    PHONEMED TEXT,
    STATUSDOC TEXT NOT NULL DEFAULT 'Active',
    TYPEDOC TEXT NOT NULL DEFAULT 'General',
    SPECIALDOC NOT NULL 
    INTVALATTDOC INTEGER NOT NULL,
    FOREIGN KEY (CODUSER) REFERENCES USERS(CODUSER),
    CHECK (STATUSDOC IN ('Active', 'Inactive')),
    CHECK (GENDOC IN ('Male', 'Female')),
    CHECK (TYPEDOC IN ( 'Doctor', 'Therapist'),
    CHECK (SPECIALDOC IN ('Neural_therapy', 'Chiropractor', 'Pysiotherapy')
);
