server.servlet.context-path=/piedraAzul/
spring.application.name=auth-service
server.port=8081

# Base de datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=piedraAzul
spring.datasource.password=PiedraAzul_DB#2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.security.user.name=admin
spring.security.user.password=admin

#Conexion con RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#JWT TOKEN
jwt.secret=p13dr4AzUl$3cR3t#K3y!2024@M1cr0S3rv1c10s$P13dR4#AzUl!
jwt.expiration=86400000